First version
distributed-technologies/syncctl pull request #1
Opened 2021-11-15 14:45 UTC by klausenbusk

2021-11-17 07:57 UTC, jacobcrawford requested changes
Because of CRDs the implementation of how to extract images does not scale.

2021-11-17 07:57 UTC, jacobcrawford commented on syncctl.py
> +        if d["kind"] == "CronJob":
With this implementation we will need to update the tool to support all CRDs:
For example:
```
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  # ...
  build: (1)
    output: (2)
      type: docker
      image: my-registry.io/my-org/my-connect-cluster:latest
      pushSecret: my-registry-credentials
    plugins: (3)
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://ARTIFACT-ADDRESS.tgz
            sha512sum: HASH-NUMBER-TO-VERIFY-ARTIFACT
```
I would say that this solution does not scale.

2021-11-17 10:01 UTC, jacobcrawford commented on README.md
> +`syncctl` needs a `manifest.json` file (see [`manifest.json.sample`](manifest.json.sample) for a example)
What does this manifest.json file contain? I think we need a little more than an example.

2021-11-17 10:08 UTC, jacobcrawford commented
When i try to run the script I get this:
![image](https://user-images.githubusercontent.com/22328547/142180423-87620231-17d2-4d43-9ef0-ccd33c015a61.png)
It might be something of a version problem. We should describe requirements needed in the script.

2021-11-17 10:47 UTC, jacobcrawford requested changes
The only big question i have is what the manifest file is for :)

2021-11-17 10:47 UTC, jacobcrawford commented on syncctl.py
> +        basicConfig(level=DEBUG)
```suggestion
        basicConfig(level=logging.DEBUG)
```
DEBUG is not defined, You need to import logging and use the package.

2021-11-17 12:05 UTC, jacobcrawford commented on syncctl.py
> +                    "image": image[image.index("/")+1:min(image.index(":"), image.index("@"))],
image.index() will throw an exception if "@" is not in the string. The opposite check on l. 164 should apply here.

2021-11-17 17:40 UTC, klausenbusk commented
> This is because the script use python3.10 features. We should specify that this is a requirement for the script.
> skopeo is also needed.

It is a [python3.9 feature](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections), but yes the requirements should be documented. The PR is draft for a reason :)

2021-11-17 17:48 UTC, klausenbusk commented on syncctl.py
> +        if d["kind"] == "CronJob":
We are aware, but not a priority right now. I do have a alternative PoC implementation (looking at all `image` key), which should be more scalable tho.

2021-11-17 19:05 UTC, jacobcrawford commented on syncctl.py
> +        if d["kind"] == "CronJob":
Why is it not a priority right now? We are using a lot of CRDs in e.g. Kafka and Ceph. These will not be extracted with this implementation?

2021-11-17 21:14 UTC, klausenbusk commented on syncctl.py
> +        if d["kind"] == "CronJob":
We aren't blocked by missing images (yet), but more urgent tasks (ex: mirroring all the Helm charts).

We'll cross that bridge when we get to it :) (soon™)

2021-11-29 11:20 UTC, klausenbusk commented on README.md
> +`syncctl` needs a `manifest.json` file (see [`manifest.json.sample`](manifest.json.sample) for a example)
I have described the manifest file in the README.

2021-11-29 21:43 UTC, skovbakke requested changes
Some smaller changes

2021-11-29 21:43 UTC, skovbakke commented on syncctl.py
> +    if manifest["mediaType"] == "application/vnd.docker.distribution.manifest.list.v2+json" or manifest["mediaType"] == "application/vnd.oci.image.index.v1+json":
Split this over two lines
```suggestion
    if (manifest["mediaType"] == "application/vnd.docker.distribution.manifest.list.v2+json"
            or manifest["mediaType"] == "application/vnd.oci.image.index.v1+json"):
```

2021-11-29 21:43 UTC, skovbakke commented on syncctl.py
> +            if m["platform"]["architecture"] == "amd64" and m["platform"]["os"] == "linux":
Split this in two as well
```suggestion
            if (m["platform"]["architecture"] == "amd64" 
                    and m["platform"]["os"] == "linux"):
```

2021-11-29 21:43 UTC, skovbakke commented on syncctl.py
> +#    return json.loads(p.stdout)["Digest"]
```suggestion
```

2021-11-30 07:19 UTC, klausenbusk commented on syncctl.py
> +            file = "work/helm-chart-repo.tmp/" + os.path.basename(url)
It is required for changing the URL to a relative URL.

2021-11-30 15:43 UTC, skovbakke commented on syncctl.py
> +            file = "work/helm-chart-repo.tmp/" + os.path.basename(url)
I see, maybe we should add a comment?
```suggestion
            url = c["urls"][0]
            # edit the index in place to set a relative url
            c["urls"][0] = os.path.basename(url)
            file = "work/helm-chart-repo.tmp/" + os.path.basename(url)
```

2021-12-03 09:55 UTC, skovbakke requested changes

2021-12-03 09:55 UTC, skovbakke commented on syncctl.py
> +    name=f"{int(time.time())}"
I think we should use something more readable than a unix timestamp.

2021-12-06 08:51 UTC, klausenbusk commented on syncctl.py
> +    name=f"{int(time.time())}"
Perhaps a RFC3339 timestamp `2021-12-06T09:50+01:00.tar`?

2021-12-06 20:00 UTC, skovbakke commented on syncctl.py
> +    name=f"{int(time.time())}"
Yes, I think that would be better. It is more readable 😁

2021-12-06 20:21 UTC, skovbakke commented on syncctl.py
> +        if d["kind"] == "CronJob":
I do not think we need a feature to parse all operator specific CRDs at this point. We have an option of providing a list of images as extra images that the operator can deploy. This is in my opinion good enough.

2021-12-07 11:34 UTC, jacobcrawford commented on syncctl.py
> +        if d["kind"] == "CronJob":
If we skip this feature for not we should create a task on a more generic solution. We should do this before more applications are deployed on User Space. If this task is created I can accept the current state :)

2021-12-07 11:43 UTC, jacobcrawford commented
Should we add a JSON schema for the manifest file, or is this also a feature for later? 
![image](https://user-images.githubusercontent.com/22328547/145023198-cb3704d4-a084-44af-a448-a4883d7686c7.png)

2021-12-07 13:43 UTC, klausenbusk commented
> Should we add a JSON schema for the manifest file

I'm not sure a JSON schema is the best solution, it is meant for programmatic consumption. Thoughts? It should be easy to add, so I can add it now if desired.

2021-12-07 18:23 UTC, skovbakke commented on syncctl.py
> +        if d["kind"] == "CronJob":
I think we need to remember that this tool is only needed because of our very temporary setup.

2021-12-07 18:40 UTC, skovbakke commented on syncctl.py
> +    name=f"{datetime.datetime.now().astimezone().isoformat(timespec='seconds')}"
You can pass the `timezone.utc` to `now()` and then there is no need to convert it to utc with `astimezone()`. Also `.isoformat()` returns a string, so we no longer need the formatting.

2021-12-07 18:44 UTC, skovbakke requested changes
Minor edit

2021-12-07 19:04 UTC, klausenbusk commented on syncctl.py
> +    name=f"{datetime.datetime.now().astimezone().isoformat(timespec='seconds')}"
If we want the time to be in UTC, do we? Right now it uses the local timezone.

2021-12-07 19:06 UTC, skovbakke commented on syncctl.py
> +    name=f"{datetime.datetime.now().astimezone().isoformat(timespec='seconds')}"
Well, then `astimezone()` does nothing. `now()` also uses local timezone when you do not specify timezone.

2021-12-07 19:08 UTC, skovbakke commented on syncctl.py
> +    name=f"{datetime.datetime.now().astimezone().isoformat(timespec='seconds')}"
I think we should specify the timezone we want. Either `utc` or `Europe/Copenhagen`.

2021-12-07 19:09 UTC, klausenbusk commented on syncctl.py
> +    name=f"{datetime.datetime.now().astimezone().isoformat(timespec='seconds')}"
Nicht:
![image](https://user-images.githubusercontent.com/1080056/145090895-7f992fd6-5d1e-4739-b1a3-7a85fe1df9ed.png)

2021-12-07 19:12 UTC, skovbakke commented on syncctl.py
> +    name=f"{datetime.datetime.now().astimezone().isoformat(timespec='seconds')}"
![image](https://user-images.githubusercontent.com/78202835/145091339-40a3d1a4-4dfe-49a3-96bc-a9609750b363.png)

2021-12-07 19:15 UTC, skovbakke commented on syncctl.py
> +    name=f"{datetime.datetime.now().astimezone().isoformat(timespec='seconds')}"
So i guss the difference is that when `tz=None` there is no timezone info in the output. If you provide a timezone input to `now()` it will have timezone info in the output. 
My suggestion is still to provide the timezone we want explicitly, eg: 
```python
datetime.datetime.now(timezone.utc).isoformat(timespec='seconds')
```

2021-12-07 19:16 UTC, klausenbusk commented on syncctl.py
> +    name=f"{datetime.datetime.now().astimezone().isoformat(timespec='seconds')}"
Sounds like we kinda talked past each other.

Does this sounds good?
```
>>> datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds')
'2021-12-07T19:15:38+00:00'
```

2021-12-07 19:17 UTC, skovbakke commented on syncctl.py
> +    name=f"{datetime.datetime.now().astimezone().isoformat(timespec='seconds')}"
Perfect.

2021-12-08 05:48 UTC, skovbakke approved these changes
LGTM 🎉

2021-12-13 13:04 UTC, jacobcrawford approved these changes
If this is just temporary, I think the state is acceptable.

2021-12-13 13:34 UTC, merged