Feature/resolve images in helm chart values
distributed-technologies/syncctl pull request #12
Opened 2023-04-03 13:47 UTC by nashton

2023-04-04 05:40 UTC, jacobcrawford requested changes
Great with the tests! 
I think while the code is fresh in memory, we should add some docstrings to the functions.
It would help the readers, maintainers, and reviewers a lot :)

2023-04-04 05:40 UTC, jacobcrawford commented on syncctl.py
> +def get_helm_releases(config: dict, manifests: str) -> tuple[dict, list[dict]]:
We should add a docsstring to the method that describes what is returned, and the input parameters.

2023-04-04 05:40 UTC, jacobcrawford commented on syncctl.py
> +def mirror_charts(config: dict, manifest: dict, manifest_file: str) -> None:
can we add docstrings here as well? Seems like there is a lot of implicit knowledge lost here.
Why does the function take both a manifest and a manifest file?
 Where are the charts mirrored and in what format?

2023-04-04 05:40 UTC, jacobcrawford commented on syncctl.py
> +def template_charts(api_versions: list[str], values: dict[str, str], helm_releases: list[dict], helm_charts: list[Path]) -> Generator[int, None, None]:
This could also benefit from docstrings.

2023-04-04 05:40 UTC, jacobcrawford commented on syncctl.py
> +    null, helm_releases = get_helm_releases(config, manifests)
Is 'null' unused?
I think we should stick to the "_" for unused return variables. It is the most general syntax across different languages.

2023-04-04 05:40 UTC, jacobcrawford commented on .github/workflows/pytest.yml
> +          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
Don't we always have a requirements file?
Why is this check necessary?

2023-04-04 08:28 UTC, nashton commented on .github/workflows/pytest.yml
> +          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
No not in this repository, but if it is added later, the pipeline supports it.

2023-04-04 09:01 UTC, nashton commented on syncctl.py
> +def template_charts(api_versions: list[str], values: dict[str, str], helm_releases: list[dict], helm_charts: list[Path]) -> Generator[int, None, None]:
Done

2023-04-04 09:14 UTC, nashton commented on .github/workflows/pytest.yml
> +          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
And now I added the requirements.txt, as the script has dependencies 😀
I think it is fine to keep the check, as it is a generic thing, to make the pipeline usable in other environments.

2023-04-04 10:10 UTC, jacobcrawford requested changes
a few questions to the types

2023-04-04 10:10 UTC, jacobcrawford commented on syncctl.py
> +        api_versions: Limit to specific api versions
api versions of what?

2023-04-04 10:10 UTC, jacobcrawford commented on syncctl.py
> +        values: Values to use for templating the charts
Is the mapping chart-name -> values, or how is the dict constructed? How can a string be yaml input to a helm chart?

2023-04-04 10:10 UTC, jacobcrawford commented on syncctl.py
> +    Return: Generator for templated helm charts
The generator is returning an int, how can this be helm charts?

2023-04-04 10:48 UTC, nashton commented on syncctl.py
> +        api_versions: Limit to specific api versions
Not sure. It is for the helm template command, but not something we use. I believe it is out of scope for this PR.

2023-04-04 11:11 UTC, nashton commented on syncctl.py
> +    Return: Generator for templated helm charts
The type hinting seems to be wrong, as it is actually bytes, which then is retyped as a string. I considered it out of scope, as it is code I have not changed in this PR. I fixed the return type of template_chart and template_charts.

2023-04-04 11:11 UTC, nashton commented on syncctl.py
> +        tuple with list of helm repositories and list of helm charts
Removed types from doc, as it is already specified in method signature.

2023-04-05 07:56 UTC, jacobcrawford approved these changes
The tests somehow failed, but I reran them with success! LGTM! 🥳

2023-04-05 12:05 UTC, merged