Syncctl improvements
distributed-technologies/syncctl pull request #2
Opened 2022-02-02 15:00 UTC by klausenbusk

Improvements:
- [x] Support multiple Helm repositories
- [ ] Support creating incremental tarballs

2022-02-09 10:52 UTC, skovbakke requested changes
In general I do not like the dictionaries named `c`. The functions with an argument named `c` should find a new name for it, i.e. `mirror_images`, `mirror_yggdrasil`, `resolve_images`. 

The places where we change `c` in place are misleading, since that is the same as changing the `manifest` dictionary. I suggest that the functions that end up calling `save_manifest` make it clear what is happening by unpacking `c` inside the function, i.e. `mirror_charts` is good but `mirror_images` is confusing (see the comments for that function) and should be changed.

The new functionality looks good 😁

2022-02-09 10:52 UTC, skovbakke commented on syncctl.py
> +        mirror_images(manifest["images"], args.incremental, manifest)
We do we pass both the dictionary and an element of the dictionary? We could simply unpack the dictionary inside the function.

2022-02-09 10:52 UTC, skovbakke commented on syncctl.py
> +def mirror_images(c: dict, incremental: bool, manifest: dict) -> None:
c is not a good variable name.

2022-02-09 10:52 UTC, skovbakke commented on syncctl.py
> +            c[i]["skip"] = True
`c` is a dictionary, do you really need to enumerate it? and should it not be indexed with `image`, i.e. `c[image]["skip"] = true`

2022-02-09 10:52 UTC, skovbakke commented on syncctl.py
> +    manifest["images"] = c
This has no effect. `c` already references the same dictionary as `manifest["images"]` since `manifest["images"]` is what is passed as `c` in L:299.

2022-02-09 10:52 UTC, skovbakke commented on syncctl.py
> +        # FIXME: This isn't scalable
I agree.

2022-02-09 15:03 UTC, klausenbusk commented on syncctl.py
> +        # FIXME
The parameter isn't used. Removed in the relevant commit.

2022-02-09 15:06 UTC, klausenbusk commented on syncctl.py
> +            c[i]["skip"] = True
`c` is a list of images :)

2022-02-09 15:13 UTC, klausenbusk commented on syncctl.py
> +        # FIXME: This isn't scalable
Is this a blocker? I don't have a quickfix.

2022-02-09 15:15 UTC, klausenbusk commented on syncctl.py
> +    manifest["images"] = c
uh, yeh.

2022-02-09 15:28 UTC, klausenbusk commented on syncctl.py
> +def mirror_charts(manifest: dict) -> None:
Yes, done.

2022-02-09 15:29 UTC, klausenbusk commented on syncctl.py
> +def mirror_images(c: dict, incremental: bool, manifest: dict) -> None:
It was approved in https://github.com/distributed-technologies/syncctl/pull/1 ?! ;) Fixed.

2022-02-09 15:29 UTC, klausenbusk commented on syncctl.py
> +            c[i]["skip"] = True
I renamed the parameter to `images`, should make its purpose more clear.

2022-02-09 15:46 UTC, klausenbusk commented on syncctl.py
> +        mirror_images(manifest["images"], args.incremental, manifest)
Fixed. The idea was to make it clear which elements from the manifest variable is used.

2022-02-14 10:11 UTC, skovbakke requested changes
Looks very good. A few quality of life improvements. 

Also, in case `load_manifests` fails because the user did not provide a `manifest.json` file, then we should have an error message, e.g. "No `manifest.json` provided. Please read the documentation"

2022-02-14 10:11 UTC, skovbakke commented on syncctl.py
> +    images = manifest["images"]
Perhaps, we should provide a good error message if `manifest["images"]` does not exist? e.g. "Run `resolve_images` to generate images list".

2022-02-15 12:35 UTC, klausenbusk commented on syncctl.py
> +    for dir in ["work/helm-chart-repo.tmp", "work/yggdrasil/yggdrasil/charts"]:
Added.

2022-02-15 12:36 UTC, klausenbusk commented on syncctl.py
> +    images = manifest["images"]
Added

2022-02-15 14:50 UTC, skovbakke approved these changes
LGTM 🥳

2022-02-16 11:32 UTC, MadsHT submitted a review, later dismissed
LGTM

2022-02-17 08:21 UTC, klausenbusk commented
Fixed a rebase error:
```diff
diff --git a/syncctl.py b/syncctl.py
index bfd407b..61d7108 100755
--- a/syncctl.py
+++ b/syncctl.py
@@ -51,7 +51,7 @@ def mirror_yggdrasil(yggdrasil_config: dict) -> None:
         repo = git.Repo('work/yggdrasil')
     if repo.head.object.hexsha != yggdrasil_config["commit"]:
         repo.git.fetch()
-        repo.git.update_ref('--hard', yggdrasil_config["commit"])
+        repo.git.reset('--hard', yggdrasil_config["commit"])

 def download_file(url: str, dest: str, hash: str = None) -> None:
     with requests.get(url) as r:
```

2022-02-17 08:22 UTC, skovbakke approved these changes
LGTM 😊

2022-02-17 08:23 UTC, merged